### ISSUE TITLE
Consider moving the IFileSystem from GitVersion to GitTools.Core

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitTools.Core#21]
@JakeGinnivan Is GitVersion already using this core? If so, we can safely move it here.

**Comment by pascalberger** [comment]
@GeertvanHorrik Shouldn't the namespace also be adapted (is still `GitVersion.IO`)

**Comment by GeertvanHorrik** [comment]
Good catch, already fixed that :-)

**Comment by JakeGinnivan** [comment]
Why don't we use System.IO.Abstractions rather than having to maintain this as part of our public api

**Comment by GeertvanHorrik** [comment]
Good point. I just copy/pasted this one from GitVersion.

**Comment by GeertvanHorrik** [comment]
See #24
