### ISSUE TITLE
Setup proper build/deploy pipeline with Cake

### ISSUE THREAD

**Issue by JakeGinnivan** [GitTools/GitTools.Core#35]
Mirror after GitVersions

**Comment by asbjornu** [comment]
How's the progress of this? 😃

**Comment by dazinator** [comment]
Closing as we have travis and appveyor builds. Please re-open if I have got this wrong.

**Comment by gep13** [comment]
@dazinator I think the suggestion here was to use Cake in the same way that the main GitVersion repository does, so that it handles everything from the build, all the way through to the deployment of the nupkg's (assuming that there are some).

**Comment by asbjornu** [comment]
Correct. Reopening.

**Comment by dazinator** [comment]
I think its going to be a million times easier to just add an appveyor nuget deployment provider on tot he appveyor.yaml. AppVeyor is already doing everything we need it to, including running the unit tests. Im happy to do this if someone wants to give me permissions for AppVeyor.

**Comment by dazinator** [comment]
For an example of that see: https://github.com/dazinator/Dotnettency/blob/master/appveyor.yml#L22

**Comment by GeertvanHorrik** [comment]
@dazinator please check gitter.

**Comment by asbjornu** [comment]
@dazinator: Well, NuGet is not the only deployment target. We want to push packages to VSTS, Homebrew, Apt, NPM, etc., too.

**Comment by dazinator** [comment]
@asbjornu For the GitTools.Core assembly?

**Comment by asbjornu** [comment]
@dazinator: Ah, no. You're correct.

**Comment by dazinator** [comment]
@asbjornu - :-)
In that case - I think this can now be closed. If there is something that the build needs to be amended for specifically, we can raise a more specific issue for what that work should be!

**Comment by asbjornu** [comment]
Sure. A more precise issue might be "Auto-deploy NuGet package". A PR implementing that with AppVeyor would be great. 😃

**Comment by dazinator** [comment]
That is already done.. see my commit further up on this issue.
