### ISSUE TITLE
Port to NETStandard

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitTools.Core#40]
### Feature description

Port the solution NETStandard.
This will unlock ability to port GitVersionTask to .NETStandard.
This will unlock dotnet cli builds for projects that consume GitVersionTask

Here is the API Portability analysis: [ApiPortAnalysis.xlsx](https://github.com/GitTools/GitTools.Core/files/1109042/ApiPortAnalysis.xlsx)

**Comment by dazinator** [comment]
Blocker for this at the moment is that libgit2sharp nugget package that supports netstandard1.3 hasn't been released to nuget yet..

**Comment by dazinator** [comment]
I have started work in a branch but it's not yet successfully building. 

1. Moved all the code into a netstandard 1.3 project, and deleted the net4, net45 and shared projects.
2. Tried to resolve all compilation errors, by adding relevant dependencies back, however some aren't yet available..

Couldn't resolve:

1. LibGit2Sharp
2. ` [StringFormatMethod("format")]` attribute
3. `using JetBrains.Annotations;`
4. `SerializationInfo`

**Comment by dazinator** [comment]
Have attached an API portability analysis: [ApiPortAnalysis.xlsx](https://github.com/GitTools/GitTools.Core/files/1109042/ApiPortAnalysis.xlsx)

**Comment by pdrhsm** [comment]
@dazinator 
**2**. StringFormatMethod is just a ReSharper helper-attribute as far as I know.
**3**. Latest version, 10.4.0, supports netstandard1.0-- or one could remove the annotations.
**4**. Just took a quick look,.. I can't see that [WarningException](https://github.com/GitTools/GitTools.Core/blob/1e4f94df95023dc56e24623b33fce96a602457c5/src/GitTools.Core/GitTools.Core.Shared/Exceptions/WarningException.cs) ever gets serialized, but I might be missing something.

**Comment by dazinator** [comment]
Yeah the serialisation constructor for exceptions used to be a best practice. Im not sure its required anymore though..

**Comment by conniey** [comment]
> [StringFormatMethod("format")] attribute (no idea how to replace this - perhaps need compilation directive.)
> using JetBrains.Annotations;

I would add a compiler directive for these ReSharper features based on the platform you are currently viewing in the editor, so at least if they switch to the full .NET Framework, these features will still work for them. (ie. #if NET45)
[Edit: never mind, it appears from pdrhsm's comment that it is supported on .NETStandard 1.0 now]

![image](https://user-images.githubusercontent.com/10136526/27745460-3ef591f8-5d78-11e7-9111-6d266ee2d5fd.png)

> SerializationInfo - (no idea how to replace this - perhaps need compilation directive.)

Since binary serialization is not supported until .NET Standard 2.0, I have been using compiler directives to comment this feature out

**Comment by JakeGinnivan** [comment]
Happy to just remove all blockers, rather than solving

**Comment by pdrhsm** [comment]
Removed SerializationInfo and updated to newer version of JetBrain.Annotations [here](https://github.com/pdrhsm/GitTools.Core/tree/feature/netstandard). 

I was unable to push my commits to GitTools.Core@feature/netstandard.

**Comment by conniey** [comment]
@pdrhsm As a workaround for LibGit2Sharp not having a Portable library... to continue working, in my GitTools.Testing PR, I modified the csproj to conditionally include the portable library version depending on the TargetFramework. [GitTools.Testing.Tests.csproj#L32-L40](https://github.com/conniey/GitTools.Testing/blob/d1b323b83a5c956d2f008477439b1b70e922d098/src/GitTools.Testing.Tests/GitTools.Testing.Tests.csproj#L32-L40)

Also, you should open a [PR](https://github.com/GitTools/GitTools.Core/pulls) against feature/netstandard if you want to merge your changes in.

**Comment by dazinator** [comment]
@pdrhsm I have submitted a PR on your behalf and merged those changes in, thank you.
@conniey - good idea, I'll use the same approach for now.

**Comment by dazinator** [comment]
Now that GitTools.Core is targeting netstandard1.3 - The `GitTools.Core.Tests` project which is `net45` can't reference it. I'm going to re-target the tests project to `net46` to resolve this..

**Comment by dazinator** [comment]
The next blockers are all with `ProcessHelper` - it uses `ProcessStartInfo`, `Process` and it's kin. These are all not available until NETStandard2.0 - https://github.com/dotnet/corefx/issues/12797

The sole usage for the `ProcessHelper` within GitTools.Core is for the `DumpGraph()` method - because it shells out to `git`.

**Comment by dazinator** [comment]
Ok I think this can be reviewed now. I ended up cross compiling for `netstandard` and `net452` and dropping `DumpGraph` in the netstandard build - because of the lack of system.diagnostic.process api's.

**Comment by dazinator** [comment]
PR Submitted.

**Comment by dazinator** [comment]
Having issues with Travis build as we can't build under mono anymore now that we are using the new csproj style / format. AppVeyor is fine. I think on Travis we should be able to build using `dotnet cli` under `netcoreapp` instead - but this requires GitTools.Testing to add support for that platform.

**Comment by dazinator** [comment]
Waiting on https://github.com/GitTools/GitTools.Testing/pull/6 to be merged, so can then get the tests on travis to run under netcoreapp.

**Comment by pdrhsm** [comment]
@dazinator as far as I can see this seems to be done? 

If so; when can we expect as release?! 👍

**Comment by dazinator** [comment]
@pdrhsm - `GitTools.Core` was released to nuget: https://www.nuget.org/packages/GitTools.Core/
