### ISSUE TITLE
Gitlink - build not pinned to particular version, new version breaking

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitTools.Core#43]
Last successful build, using gitlink 2.4.1
https://ci.appveyor.com/project/GitTools/gittools-core/build/1.2.1-netstandard.1+27.build.165#L29

build kicked off today, and pulled in 3.0.0 - which fails:
https://ci.appveyor.com/project/GitTools/gittools-core/build/1.2.1-beta.2+28.build.167#L376

Need to pin the build to use 2.4.1 until we know what we need to change to upgrade.

**Comment by GeertvanHorrik** [comment]
Correct, it's unfortunate that chocolatey installs the latest (which is great) but doesn't require a manual step for breaking changes (major releases). This was one of the reasons it took me so long to actually release GL 3.0

**Comment by dazinator** [comment]
Haha, well I just raised an issue over on GitLink for this as I was curious to know what the new command like should look like :-) I'll pin it for now and we can upgrade seperately in due course.

**Comment by dazinator** [comment]
I can't believe you can't restrict it to a version range.. :-(
