### ISSUE TITLE
Consider to make JetBrains.Annotations dependency private.

### ISSUE THREAD

**Issue by GreenKn1ght** [GitTools/GitTools.Core#50]
As decribed [here](https://www.nuget.org/packages/JetBrains.Annotations), no actual binary reference to 'JetBrains.Annotations.dll' assembly is produced when using JetBrains.Annotations nuget package without JETBRAINS_ANNOTATIONS compilation symbol defined. This mean there is no actual dependency.

**Comment by borrrden** [comment]
This also means that any library that is already doing this will suddenly get hundreds of warnings about duplicated types.

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this PR is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
