### ISSUE TITLE
Create gittools.readme.io with explanation of all the tools

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitTools.Core#7]
We should create a centralized page with docs:

* gittools.readme.io => show everything (all tools and how they work together)
* gitlink.readme.io
* gitversion.readme.io
* gitreleasenotes.readme.io
* gitreleasemanager.readme.io

**Comment by GeertvanHorrik** [comment]
All projects are created.

**Comment by GeertvanHorrik** [comment]
Can't give other people access, it's a premium feature.

**Comment by JakeGinnivan** [comment]
They have oss licences, just request and then you can put voucher in which pays for it

Sent from my Windows Phone
________________________________

**Comment by GeertvanHorrik** [comment]
Requested license, set up the basics for all urls. Once we have the license I will invite everyone.

**Comment by gep13** [comment]
Yeah, would be great to have access to the pages, that way I can port the pages from the existing project over to the new one, or better, simply rename the existing project that I have to gitreleasemanager.

**Comment by GeertvanHorrik** [comment]
Everyone is invited, projects created. We can improve them continuously

**Comment by GeertvanHorrik** [comment]
Received license and applied it.
